"""Add engineered columns

Revision ID: a0da3e14a96d
Revises: f5823a2ca079
Create Date: 2026-06-14 14:59:27.642836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0da3e14a96d'
down_revision: Union[str, Sequence[str], None] = 'f5823a2ca079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('duration_minutes', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('energy_level', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('danceability_level', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('tempo_category', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('popularity_bucket', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'popularity_bucket')
    op.drop_column('tracks', 'tempo_category')
    op.drop_column('tracks', 'danceability_level')
    op.drop_column('tracks', 'energy_level')
    op.drop_column('tracks', 'duration_minutes')
    # ### end Alembic commands ###
